name: Nightly Corpus Test

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/corpus_test.yml
    with:
      CORPUS_GITHUB_PATH: cgc-challenges/windows-build/challenges/Estadio;cgc-challenges/linux-build64/challenges/Estadio;cgc-challenges/linux-build/challenges/Estadio
      NIGHTLY_CORPUS_TEST: 1
